### ISSUE TITLE
Race condition issue

### ISSUE THREAD

**Issue by natilivni** [maxlaverse/snat-race-conn-test#2]
Hello,

I just came across your article on this matter here: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

It seems to us that this may be causing errors for us when we do bulk inserts to a central database.

I was wondering if you found any way to remediate this issue on k8s?

**Comment by maxlaverse** [comment]
Hi @natilivni,
Back then, we switched the network plugin to have routable Pod IPs (Calico+BGP). This removed the need for masquerading when reaching IPs outside the cluster but on the "local" network, and therefore removed the problem. Since then, I've always worked with clusters that have routable Pod IPs.

If you can't do this kind of change (e.g. use Calico+bgp or aws-cni), you need to reduce the amount of new connections opened concurrently to the same IP+Port:
* if you use a pool of database connections, you could maybe hook into the step where new connections are created and ensure this is done sequentially. Eventually you could also build up the database pool when your application starts, to avoid having to do it suddenly on runtime.
* if you're able to expose your database behind multiple IP:Port pairs, that would reduce the likelihood to have a clash as well. 
* if your application is trashing a lot of database connections (opening then closing rapidly), leaving them open for a while (using a pool) would reduce the amount of new connections being established and again, reduce the likelihood for a race. We discovered the issue with HTTP connections and 'Connection: Keep-Alive' definitely helped.
* note: once I talked to someone who thought SNAT was the issue when it was actually the bandwidth limit of EC2 instances (if you run on AWS).
* going experimental: you might be able to delay SYN packets with 'tc' or maybe do something with eBGP. Never tried it myself.
* finally, some changes were pushed in "recent" Linux Kernel version (5.10+?) in this area (connection tracking). Upgrading might help but I don't remember exactly what the changes were about tbh.

The '--random-fully' flag I talked about in the article is very often set nowadays even you have recent version of Kubernetes and network plugins.

That's all I can think of so far.

**Comment by natilivni** [comment]
Thank you for the thorough comment. very helpful!
